In [29]:
w1, w2, w3 = 0.3, 0.2, 0.5
weights= [w1, w2, w3]
weights

[0.3, 0.2, 0.5]

In [23]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

56.8

In [26]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

#creating a function for the job
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result
crop_yield(kanto, weights)


56.8

#               using numpy arrays

In [19]:
import numpy as np

In [20]:
kanto = np.array([73, 67, 43])

In [7]:
kanto

array([73, 67, 43])

In [31]:
weights = np.array ([w1, w2, w3])
weights

array([0.3, 0.2, 0.5])

In [32]:
type(weights)

numpy.ndarray

In [34]:
np.dot(kanto, weights)

56.8

In [36]:
kanto * weights

array([21.9, 13.4, 21.5])

In [39]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr1 * arr2
np.dot( arr1, arr2 ) #this sum it all up as one


array([ 4, 10, 18])

In [46]:
#python list and NP arrays
arr1 = list(range(1000000))
arr1
len(arr1)
arr2 = list(range(1000000, 2000000))
arr2
len(arr2)
# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [66]:
type(arr1)
type(arr1_np)
type(weights)
weights.dtype

dtype('float64')

In [67]:
# multi dimentionsal
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
climate_data
climate_data.shape #dimention of the arrays (R,C) format
weights
weights.shape
type(climate_data)


dtype('int32')

In [57]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])
arr3.shape

(2, 2, 3)

In [58]:
arr3

array([[[11. , 12. , 13. ],
        [13. , 14. , 15. ]],

       [[15. , 16. , 17. ],
        [17. , 18. , 19.5]]])

In [71]:
climate_data.dtype
arr3.dtype

dtype('float64')

In [72]:
np.matmul(climate_data, weights) #gives correspoding np.dot mult values
climate_data @ weights # alternative form

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [75]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')


('climate.txt', <http.client.HTTPMessage at 0x1fb10d3ce80>)

In [76]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [80]:
type(climate_data)
climate_data.shape
climate_data.size
weights = np.array([0.3, 0.2, 0.5])

In [84]:
yields = climate_data * weights # thiis multiply through without given a value summed
yields = climate_data @ weights #this give elements summed

In [85]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [87]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)
climate_results.shape
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [91]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])


In [92]:
arr2.shape
# Modulus with scalar
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)

In [100]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])
arr1 == arr2
arr1 != arr2
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [101]:
(arr1 != arr2).sum() #knowing total items from indexing

3

In [103]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

# Subarray using ranges
arr3[1:, 0:1, 2:]

array([[[17., 21.]],

       [[81., 23.]]])

In [104]:
# Subarray using ranges
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [106]:
# Subarray using ranges
arr3[1:, 1:, :2]
arr3[1:, 1, 3]

array([18., 43.])

In [108]:
arr3

array([[[11. , 12. , 13. , 14. ],
        [13. , 14. , 15. , 19. ]],

       [[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [109]:
# Using fewer indices
arr3[1]
arr3[:2,1]


array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])